<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [2]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.395839   0.21379428 0.07247983 ... 0.64980615 0.64291476 0.32526086]
 [0.99447693 0.63253878 0.10648252 ... 0.09038331 0.08219018 0.63331995]
 [0.03470463 0.83264811 0.00266264 ... 0.41459466 0.20456353 0.88582864]
 ...
 [0.6902504  0.10926463 0.64770747 ... 0.7091193  0.19629277 0.9975028 ]
 [0.64204202 0.65320852 0.35489944 ... 0.00704072 0.78367391 0.59237454]
 [0.84137914 0.89991396 0.55261748 ... 0.3186097  0.48761123 0.91937383]]
[[0.19223844 0.02409304 0.41697875 ... 0.2896223  0.03328157 0.64914984]
 [0.59910385 0.40862453 0.40050159 ... 0.89650084 0.46264964 0.90442002]
 [0.87800265 0.28263125 0.82332552 ... 0.71561631 0.51356527 0.58747008]
 ...
 [0.83887046 0.24098338 0.29652699 ... 0.75683419 0.17818834 0.37654114]
 [0.26376756 0.33976523 0.95381248 ... 0.8179511  0.18956817 0.70542156]
 [0.02341907 0.56668502 0.53320765 ... 0.52531754 0.27821011 0.91949749]]


In [ ]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    pass

In [ ]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a.dot(b)

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [22]:
a = np.random.sample((1, 30000000))
b = np.random.sample((1, 30000000))
a = list(a)[0]
b = list(b)[0]
print(a, b)

[0.20233404 0.22847045 0.35204088 ... 0.61199477 0.60640867 0.68255736] [0.88942439 0.48580886 0.10284558 ... 0.93565574 0.56429071 0.02944877]


In [23]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    return sum([ai * bi for ai, bi in zip(a, b)])

In [24]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return a.dot(b)

In [25]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

Wall time: 10.2 s
Wall time: 31.2 ms


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [35]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    diag = np.diag(a)
    return diag[diag % 2 == 0].sum()

In [41]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(10, 10))

In [40]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 0 ns


22188

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [49]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    return np.cumsum(A, axis=1)

In [58]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = np.array(sps.uniform.rvs(size=10**6)).reshape(1000, 1000)
%time S2 = cumsum(A)

Wall time: 6 ms


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [142]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy
    
    """ 
    A = X.copy()
    A[:, 1::2] = 100
    A[:, ::2]**=3
    return np.concatenate((X, A[:, ::-1]), axis=1)

In [143]:
X = np.array([[i for i in range(1, 10, 2)], [i**2 for i in range(1, 10, 2)]])




# %time S2 = np_transformation(X, 5)

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [144]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    elems = []
    repet = []
    s = 1
    for i in range(0, len(X)-1):
        if X[i] != X[i+1]:
            elems.append(X[i])
            repet.append(s)
            s = 1
        else:
            s += 1
        if i == len(X)-2:
            elems.append(X[i+1])
            repet.append(s)    
            
    return elems, repet

In [242]:
X = np.array([ -1, -2, -2, -2, 3, 3, 1, 1, 5, 5, 2, 3, 3, 4, 4, 5, 5, 5, 5, 4])
# print(X)
# print('  ', np.diff(X), len(X), len(np.diff(X)))
a = np.diff(X)
a = np.append(a, 1)
print(X)
print(a)
print(X[a.astype('bool')])
idx = np.nonzero(a)
print(np.split(a, idx[0]))
        
    

print(elems, repet)
%time x, num = np_encode(X)

[-1 -2 -2 -2  3  3  1  1  5  5  2  3  3  4  4  5  5  5  5  4]
[-1  0  0  5  0 -2  0  4  0 -3  1  0  1  0  1  0  0  0 -1  1]
[-1 -2  3  1  5  2  3  4  5  4]
[array([], dtype=int32), array([-1,  0,  0]), array([5, 0]), array([-2,  0]), array([4, 0]), array([-3]), array([1, 0]), array([1, 0]), array([1, 0, 0, 0]), array([-1]), array([1])]
[-1, -2, 3, 1, 5, 2, 3, 4, 5] [1, 3, 2, 2, 2, 1, 2, 1, 1]
Wall time: 0 ns


In [252]:
def encode(a):
    is_new_in_row = np.array(a[1:] != a[:-1])
    print(a[1:], a[:-1])
    print(is_new_in_row, len(a), len(is_new_in_row))
    print(np.where(is_new_in_row))
    position = np.append(np.where(is_new_in_row), len(a) - 1)
    lengths = np.diff(np.append(-1, position))
    return (a[position], lengths)

encode(X)

[-2 -2 -2  3  3  1  1  5  5  2  3  3  4  4  5  5  5  5  4] [-1 -2 -2 -2  3  3  1  1  5  5  2  3  3  4  4  5  5  5  5]
[ True False False  True False  True False  True False  True  True False
  True False  True False False False  True] 20 19
(array([ 0,  3,  5,  7,  9, 10, 12, 14, 18], dtype=int64),)


(array([-1, -2,  3,  1,  5,  2,  3,  4,  5,  4]),
 array([1, 3, 2, 2, 2, 1, 2, 2, 4, 1], dtype=int64))

[ True False False  True False  True False  True False  True  True False
  True False  True False False False  True] 20 19


(array([-1, -2,  3,  1,  5,  2,  3,  4,  5,  4]),
 array([1, 3, 2, 2, 2, 1, 2, 2, 4, 1], dtype=int64))