In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 32700], dtype='int16')
print(a)

[    1     2 32700]


In [ ]:
arr = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]]]
)
print(arr)
print(len(arr))
print(arr.size)
print(arr.shape)
print(arr.ndim)

In [4]:
zeros = np.zeros(10, dtype='int16')
ones = np.ones(10, dtype='float16')
print(zeros)
print(ones)

[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='float64')
arr_py = [1.0, 2.0, 3]
zeros_like_arr_py = np.zeros_like(arr_py)
ones_like_arr = np.ones_like(arr)
zeros_like_arr = np.zeros_like(arr)
print(arr)
print(ones_like_arr)
print(zeros_like_arr)
print(arr_py)
print(zeros_like_arr_py, type(zeros_like_arr_py), type(zeros_like_arr_py[0]))


[1. 2. 3. 4. 5. 6.]
[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]
[1.0, 2.0, 3]
[0. 0. 0.] <class 'numpy.ndarray'> <class 'numpy.float64'>


In [6]:
a = np.arange(5)
b = np.arange(5.5, 10, 2)
c = np.arange(1, 10, 1.4) #last element not included
print(a, b, c)

[0 1 2 3 4] [5.5 7.5 9.5] [1.  2.4 3.8 5.2 6.6 8.  9.4]


In [7]:
a = np.arange(-5, 10, 2)
a2 = np.arange(-5, 10, -2)
b = np.arange(5, -10, -2, dtype='float64')
b2 = np.arange(5, -10, 2)
print(a, b)
print(a2, b2)

[-5 -3 -1  1  3  5  7  9] [ 5.  3.  1. -1. -3. -5. -7. -9.]
[] []


In [8]:
a = np.linspace(-1, 13, 8)
b = np.linspace(4.9, 12.1, 11) #first and last are included, countnity by defoult 50
print(a)
print(b)

[-1.  1.  3.  5.  7.  9. 11. 13.]
[ 4.9   5.62  6.34  7.06  7.78  8.5   9.22  9.94 10.66 11.38 12.1 ]


In [9]:
a = np.linspace(15, -1, 5)
b = np.linspace(15.1, 4.3, 6)
print(a, b)

[15. 11.  7.  3. -1.] [15.1  12.94 10.78  8.62  6.46  4.3 ]


In [10]:
print(np.logspace(-1, 3, 6, dtype='float16'))

[9.998e-02 6.309e-01 3.980e+00 2.512e+01 1.585e+02 1.000e+03]


In [11]:
a = np.linspace(1, 16, 7)
b = np.linspace(-10, -4, 7)
print(a)
print(b)
print(a + b)
print(a * b)
print(a - b)
print(a // -b)
print(a % -b)
print(a * 3)
print(a + 10)
c = np.linspace(1, 10, 10, dtype='int64')
print(c)
print(c ** 2)
print(2 ** c)
print(np.sin(c))
print(np.log(c))


[ 1.   3.5  6.   8.5 11.  13.5 16. ]
[-10.  -9.  -8.  -7.  -6.  -5.  -4.]
[-9.  -5.5 -2.   1.5  5.   8.5 12. ]
[-10.  -31.5 -48.  -59.5 -66.  -67.5 -64. ]
[11.  12.5 14.  15.5 17.  18.5 20. ]
[0. 0. 0. 1. 1. 2. 4.]
[1.  3.5 6.  1.5 5.  3.5 0. ]
[ 3.  10.5 18.  25.5 33.  40.5 48. ]
[11.  13.5 16.  18.5 21.  23.5 26. ]
[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]
[   2    4    8   16   32   64  128  256  512 1024]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [12]:
a = np.linspace(1, 16, 7)
b = np.linspace(-10, -4, 7)
print(a > -b)
print(a == b)
print(a)
print(b)
print(np.any(a == 13.5), np.any(b > -5))
print(np.all(a > 1), np.all(b < 0))

[False False False  True  True  True  True]
[False False False False False False False]
[ 1.   3.5  6.   8.5 11.  13.5 16. ]
[-10.  -9.  -8.  -7.  -6.  -5.  -4.]
True True
False True


## inplace

In [14]:
a = np.linspace(1, 16, 7)
b = np.linspace(-10, -4, 7)
print(b ** 2)
b += b ** 2
print(b)
b *= 2
print(b)

[100.  81.  64.  49.  36.  25.  16.]
[90. 72. 56. 42. 30. 20. 12.]
[180. 144. 112.  84.  60.  40.  24.]


In [15]:
a = np.linspace(1, 10, 10)
b = np.linspace(-10, -4, 7)
print(a)
print(b)
print(np.cumsum(a))
print(np.cumsum(b))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[-10.  -9.  -8.  -7.  -6.  -5.  -4.]
[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]
[-10. -19. -27. -34. -40. -45. -49.]


## union of arrays

In [17]:
a = np.linspace(1, 4, 4)
b = np.linspace(-10, -7, 4)
c = np.hstack((a, b, b*5))
print(c)
c1, c2, c3, c4 = np.hsplit(c, [1, 3, 5])
print(c1, c2, c3, c4)
c1, c2, c3, c4 = np.hsplit(c, [3, 2, 5])
print(c1, c2, c3, c4)

[  1.   2.   3.   4. -10.  -9.  -8.  -7. -50. -45. -40. -35.]
[1.] [2. 3.] [  4. -10.] [ -9.  -8.  -7. -50. -45. -40. -35.]
[1. 2. 3.] [] [  3.   4. -10.] [ -9.  -8.  -7. -50. -45. -40. -35.]


In [18]:
a = np.linspace(1, 4, 7)
b = np.delete(a, [2, 4])
c = np.insert(a, 3, b * 10 + 3)
d = np.append(a, 10*b + 3)
print(a)
print(b)
print(c)
print(d)

[1.  1.5 2.  2.5 3.  3.5 4. ]
[1.  1.5 2.5 3.5 4. ]
[ 1.   1.5  2.  13.  18.  28.  38.  43.   2.5  3.   3.5  4. ]
[ 1.   1.5  2.   2.5  3.   3.5  4.  13.  18.  28.  38.  43. ]


In [19]:
## indexes and slices


In [20]:
a = np.linspace(2, 22, 11)
print(a)
print(a[::-1])
print(a[3:9:2])
a[3:9:2] = 100
print(a)
b = a
print(b)
b[3] = -10
print(a, '\n', b)
b = np.copy(a)
b[3] = -999
print(a, '\n', b)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22.]
[22. 20. 18. 16. 14. 12. 10.  8.  6.  4.  2.]
[ 8. 12. 16.]
[  2.   4.   6. 100.  10. 100.  14. 100.  18.  20.  22.]
[  2.   4.   6. 100.  10. 100.  14. 100.  18.  20.  22.]
[  2.   4.   6. -10.  10. 100.  14. 100.  18.  20.  22.] 
 [  2.   4.   6. -10.  10. 100.  14. 100.  18.  20.  22.]
[  2.   4.   6. -10.  10. 100.  14. 100.  18.  20.  22.] 
 [   2.    4.    6. -999.   10.  100.   14.  100.   18.   20.   22.]


In [21]:
a = np.linspace(2, 22, 11)
print(a)
print(np.arange(11.0))
print(a[[1, 4, 7]])

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 4. 10. 16.]


In [22]:
a = np.linspace(-4*np.pi, 4*np.pi, 100)
summ = np.sin(a)**2 + np.cos(a)**2
print(np.all(summ.round() == 1))

True


In [23]:
## 2d-arrays

In [24]:
a = np.array([np.linspace(2, 22, 11), np.linspace(3, 33, 11)])
print(a)
print(len(a), a.size, a.shape, a.ndim)
print(a[1][2], a[1, 2])

[[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]]
2 22 (2, 11) 2
9.0 9.0


In [25]:
a = np.arange(0, 20)
print(a)
a.shape = (2, 10)
print(a)
a.shape = (4, 5)
print(a)
print(a.ravel())
a.shape = (4, 5)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [26]:
d2ones = np.ones((3, 5))
d2zeros = np.zeros((5, 3))
print(d2ones)
print(d2zeros)
print(3*np.eye(5))
d = np.diag([1, 2, 3, 4])
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [27]:
a = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 25, 3))
print(a)

[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


In [28]:
## matrix production

In [29]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a*b)
print(a @ b)
print(a.dot(b))
print(b)

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]]
[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]
[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]
[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [30]:
 ## meshgrid

In [31]:
u = np.linspace(0, 6, 4)
v = np.linspace(0, 9, 4)
print(u)
print(v)
print()
x, y = np.meshgrid(u, v)
print(x)
print()
print(y)
print(y.reshape((2, 8)))
print(y.reshape(16))

[0. 2. 4. 6.]
[0. 3. 6. 9.]

[[0. 2. 4. 6.]
 [0. 2. 4. 6.]
 [0. 2. 4. 6.]
 [0. 2. 4. 6.]]

[[0. 0. 0. 0.]
 [3. 3. 3. 3.]
 [6. 6. 6. 6.]
 [9. 9. 9. 9.]]
[[0. 0. 0. 0. 3. 3. 3. 3.]
 [6. 6. 6. 6. 9. 9. 9. 9.]]
[0. 0. 0. 0. 3. 3. 3. 3. 6. 6. 6. 6. 9. 9. 9. 9.]


In [32]:
## Eratosphenus filter algo

In [33]:
%%time
n_max = 1000
is_prime = [1]*n_max
is_prime[:2] = 0, 0
for i in range(2, int(n_max**.5) + 1):
    for j in range(i**2, n_max, i):
        is_prime[j] = 0

Wall time: 0 ns


In [34]:
%%time
n_max = 1000
numbers = np.arange(n_max)
is_primes = np.ones(n_max, dtype='bool')

is_primes[:2] = False
for i in range(2, int(n_max**.5) + 1):
    is_primes[i**2::i] = False

#if np.all(is_primes == is_prime):
#    print('wow')
#eq = is_primes == is_prime
#print(eq[eq==False])

print(numbers[is_primes])

[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359
 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463
 467 479 487 491 499 503 509 521 523 541 547 557 563 569 571 577 587 593
 599 601 607 613 617 619 631 641 643 647 653 659 661 673 677 683 691 701
 709 719 727 733 739 743 751 757 761 769 773 787 797 809 811 821 823 827
 829 839 853 857 859 863 877 881 883 887 907 911 919 929 937 941 947 953
 967 971 977 983 991 997]
Wall time: 1 ms


In [35]:
sepa = '\n'+'-'*60 + '\n'

In [36]:
a = [1]*10
b = [1]*10
print(a==b)
c = np.ones(10)
d = np.ones(10)
print(c==1)

True
[ True  True  True  True  True  True  True  True  True  True]


In [37]:
## masks

In [38]:
a = np.arange(10)
b = np.arange(18, -1, -2)

print(a % 3 == 0)
print(a[a % 3 == 0])
print(a[a % 3 == 0] > 3)
print(a[a % 3 == 0][ a[a % 3 == 0] > 3])

print()
print(a[a > 3][a[a > 3] % 3 == 0] )
print()


[ True False False  True False False  True False False  True]
[0 3 6 9]
[False False  True  True]
[6 9]

[6 9]



In [39]:
a = np.arange(20)
b = np.diag(a[a >= 10])
print(b)
trace = np.trace(b)
print(trace)

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


In [40]:
## tenzors

In [41]:
x = np.arange(48).reshape(6, 2, 4)
print(x)
print(x.shape, x.size, x.ndim, len(x))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]]
(6, 2, 4) 48 3 6


In [42]:
print(x[[3, 5]], sepa)
print(x[1], sepa)
print(x[1][0], sepa)
print(x[1][0][3], sepa)


[[[24 25 26 27]
  [28 29 30 31]]

 [[40 41 42 43]
  [44 45 46 47]]] 
------------------------------------------------------------

[[ 8  9 10 11]
 [12 13 14 15]] 
------------------------------------------------------------

[ 8  9 10 11] 
------------------------------------------------------------

11 
------------------------------------------------------------



In [43]:
foo = 0
print(x, sepa)
print(np.sum(x), 'sum all', sepa)
print(np.sum(x, axis=0), 'sum axis 0', sepa)
print(np.sum(x, axis=1), 'sum axis 1', sepa)
print(np.sum(x, axis=2), 'sum axis 2', sepa)
print(np.sum(x, axis=(0, 1)), 'sum axis 0, 1', sepa)
print(np.sum(x, axis=(0, 1)), 'sum axis 1, 0', sepa)
print(np.sum(x, axis=(1, 2)), 'sum axis 1, 2', sepa)
print(np.sum(x, axis=(2, 1)), 'sum axis 2, 1', sepa)
print(np.sum(x, axis=(0, 2)), 'sum axis 0, 2', sepa)
print(np.sum(x, axis=(2, 0)), 'sum axis 2, 0', sepa)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]] 
------------------------------------------------------------

1128 sum all 
------------------------------------------------------------

[[120 126 132 138]
 [144 150 156 162]] sum axis 0 
------------------------------------------------------------

[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]
 [68 70 72 74]
 [84 86 88 90]] sum axis 1 
------------------------------------------------------------

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]] sum axis 2 
------------------------------------------------------------

[264 276 288 300] sum axis 0, 1 
------------------------------------------------------------

[264 276 288 300] sum axis 1, 0 
------------------------------------------------------------

[ 28  92 156 220 284 348] sum axis 1, 2 
-------

In [44]:
## linalg

In [45]:
from numpy import linalg as npl
a = 3*np.eye(3) + 5 
a_inv = npl.inv(a)
print(a)
print(npl.det(a))
print(a_inv)
print(a.dot(a_inv))

[[8. 5. 5.]
 [5. 8. 5.]
 [5. 5. 8.]]
161.99999999999994
[[ 0.24074074 -0.09259259 -0.09259259]
 [-0.09259259  0.24074074 -0.09259259]
 [-0.09259259 -0.09259259  0.24074074]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.55111512e-17 1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00 1.00000000e+00]]


In [46]:
singular_matrix = np.array([[1, 2, 3], [4, 5, 6], [2, 4, 6]])
print(singular_matrix)
print(npl.det(singular_matrix))
try:
    print(npl.inv(singular_matrix))
except npl.LinAlgError as err:
    if 'Singular matrix' in str(err):
        print(err)
    else:
        raise

[[1 2 3]
 [4 5 6]
 [2 4 6]]
0.0
Singular matrix


In [47]:
## System algebraitic equation linear solving

In [48]:
b = np.array([5, -10])
a = np.array([[2, 1], [2, 3]])
a = np.eye(3) + 1
b = np.array([5, 7, 3])
print(a)
print(b, sepa)
print(npl.solve(a, b))
print(npl.inv(a) @ b)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
[5 7 3] 
------------------------------------------------------------

[ 1.25  3.25 -0.75]
[ 1.25  3.25 -0.75]


In [55]:
## Selfie vectors and values $A \prod x = \lambda \prod x$, 
## where x is eigen vector and \lambda eigen value for x for matrix A 
?????????????????????

Object `???????????????????` not found.


In [56]:
print(sepa, 'unsingular matrix eigens', *npl.eig(a), sep='\n')
l, v = npl.eig(a)
print(a @ v[0])
print(sepa, 'identity matrix eigens ', *npl.eig(np.eye(3)), sep='\n')
print(sepa, 'singular matrix eigens ', *npl.eig(singular_matrix), sep='\n')


------------------------------------------------------------

unsingular matrix eigens
[1. 4. 1.]
[[-0.81649658  0.57735027 -0.32444284]
 [ 0.40824829  0.57735027 -0.48666426]
 [ 0.40824829  0.57735027  0.81110711]]
[-1.38008573  0.01376112 -0.888032  ]

------------------------------------------------------------

identity matrix eigens 
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

------------------------------------------------------------

singular matrix eigens 
[1.17445626e+01 1.68430146e-15 2.55437353e-01]
[[-0.30674675 -0.40824829  0.24714134]
 [-0.72768959  0.81649658 -0.83343013]
 [-0.61349351 -0.40824829  0.49428268]]
